/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WaitWindow.java
 *
 * Created on May 18, 2010, 1:48:56 PM
 */
package podsyncp;

public class WaitWindow extends javax.swing.JDialog implements IProgressObject {

	private final SyncManager m_mgr;

	/** Creates new form WaitWindow */
	public WaitWindow(java.awt.Frame parent, SyncManager mgr) {
		super(parent, true);
		m_mgr = mgr;
		initComponents();
		setLocationRelativeTo(parent);

		ProcessFilesThread thread = new ProcessFilesThread(mgr, this);
		thread.start();
		setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      m_progress = new javax.swing.JProgressBar();

      setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
      setModal(true);
      setName("Form"); // NOI18N
      setResizable(false);

      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(podsyncp.PodSyncPApp.class).getContext().getResourceMap(WaitWindow.class);
      jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
      jLabel1.setName("jLabel1"); // NOI18N

      m_progress.setName("m_progress"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addComponent(m_progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(m_progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JProgressBar m_progress;
   // End of variables declaration//GEN-END:variables

	public void setProgress(int n) {
		if (m_progress != null) {
			m_progress.setValue(n);
		}
	}

	public void startProgress() {
		m_progress.setMinimum(0);
		m_progress.setMaximum(100);
		m_progress.setValue(0);
	}

	public void endProgress() {
		this.dispose();
	}
}
