CLS
'============================================================================
'=== This is canon it may look like nothing to you now                    ===
'===               it will become a wonderfull creation                   ===
'===       Original by Johann Pachelbell : Remake in basic done by        ===
'===                         B.M. Software                                ===
'============================================================================
'warning lots and lots of really high notes
PRINT "Johann Pachelbel's Canon in d"
PLAY "mlt120o4do4f#o4ao5d"
PLAY "o4c#o4eo4ao5c#"
PLAY "o3bo4do4f#o4b"
PLAY "o3ao4c#o4f#o4a"
PLAY "o3bo4do4go4b"
PLAY "o3ao3do3f#o4a"
PLAY "o3bo3do3go4b"
PLAY "o4c#o4eo4ao5c#"
PLAY "o5f#o3do3f#o4a"
PLAY "o5eo3c#o3eo4a"
PLAY "o5do3bo3do4b"
PLAY "o5c#o3ao3c#o4a"
PLAY "o4bo2go2bo3d"
PLAY "o4ao2fo2ao3d"
PLAY "o4bo2go2bo3d"
PLAY "o5c#o3ao3c#o4a"
 'second part
PLAY "mnt80l4o5d"
PLAY "p8"
PLAY "l8f#f#gf#e"
PLAY "l3d"
PLAY "l8ddedc#"
PLAY "l2o4bo5d"
PLAY "l8dco4bo5c"
PLAY "l3o4a"
PLAY "l8o4a"
PLAY "l4o4a"
PLAY "p8"
PLAY "l8o5aabag"
PLAY "l3f#"
PLAY "l8f#f#gf#edco4ao5c"
PLAY "l2d"
PLAY "l8dco4ao5c"
PLAY "l3o5c#"
PLAY "l8c#"
PLAY "l4d"
PRINT " Canon in d is the best"

