'Song I wrote in Q-basic
'Its neat and a lot better sounding than my canon song
'listen to it once no high notes
'B.M. Software
'
'B.M. Software promises never to write songs again only games and mathmatical
'Equations and other programs
'
COLOR 15: CLS : PRINT "Raiders March Written by John williams adapted by B.M. software"
PLAY "mlt220o3l3el8fl3go4l1co3l3dl8el1fl3gl8al3bl1o4fo3l3al8bo4l2cdeo3l3el8f"
PLAY "l3go4l1co4l3dl8el1fo3msl3gl8go4mll2el3do3l8go4l2el3do3l8go4l2el3do3l8go4l2e"
PLAY "l3do2l3el8fl3go3l1co2l3dl8el1fo3l3gl8al3bo4l1fo3l3al8bo4l2cdeo3l3el8fl3g"
PLAY "o4l1cl3dl8el1fo3msl3gl8go4mll2el3do3l8go4l2el3do3l8go4l2el3do3l8go4l2f"
PLAY "l3el8dl4co3l3el8dl4co2l3el8dl4co3l3co2l8bl4amso3l4ccc"
PRINT : PRINT "                          All finished"

